% header prepended to all music chunks generated by the indexer
% ------------------------ / begin
\include "../spolecne.ly"
\include "../dilyresponsorii.ly"

% reset tagline for easier image trimming
\header { tagline = "" }

% reset score title
\paper {
  scoreTitleMarkup = \markup{}
}

\layout {  
  indent = 0\cm
  short-indent = 0\cm
}
% ------------------------ / end

